Repository Wikia/design-system, pull requests merged in 2021-01, with the labels that each got.

#446 IW-4970 Update package.json
  package.json
Labels: deploy-docs-on-merge, publish-minor-on-merge

#447 IW-4970 Update package.json
  Jenkinsfile-auto-deploy
  README.md
  package.json
  scripts/set-artifactory-token.sh
Labels: deploy-docs-on-merge, publish-patch-on-merge

#449 IW-4970 Import "skip"
  tests/integration/components/global-navigation/search-test.js
Labels: deploy-docs-on-merge, publish-patch-on-merge

#450 IW-4970 Update documentation
  tests/dummy/app/templates/overview/quick-start.hbs
Labels: deploy-docs-on-merge

#451 IW-4970 Push tags on publish as well
  Jenkinsfile-auto-deploy
  package.json
Labels: deploy-docs-on-merge, publish-patch-on-merge

#452 IW-4970 Push tags on publish as well (to origin)
  package.json
Labels: deploy-docs-on-merge, publish-patch-on-merge

#453 IW-4970 Update package version
  package.json
Labels: deploy-docs-on-merge, publish-patch-on-merge

#454 IW-4970 push in two steps
  package.json
Labels: deploy-docs-on-merge, publish-patch-on-merge

#455 IW-4970 Move release script out of package json
  Jenkinsfile-auto-deploy
  package.json
  scripts/release.sh
Labels: deploy-docs-on-merge, publish-patch-on-merge

#456 IW-4970 Update contributing documentation
  CONTRIBUTING.md
  scripts/release.sh
Labels: deploy-docs-on-merge, publish-patch-on-merge

#457 IW-4970 Use bash instead of sh
  scripts/release.sh
Labels: deploy-docs-on-merge, publish-patch-on-merge

#458 IW-4970 Skip failing test
  Jenkinsfile-auto-deploy
  tests/integration/components/global-navigation/search-test.js
Labels: deploy-docs-on-merge

#459 IW-4970 Update documentation for installation and contributing
  tests/dummy/app/templates/overview/contributing.hbs
  tests/dummy/app/templates/overview/installation.hbs
Labels: deploy-docs-on-merge

#460 IW-4970 Pull changes from gh-pages branch
  Jenkinsfile-auto-deploy
Labels: deploy-docs-on-merge, publish-minor-on-merge

#461 Pills
  package.json
  style-guide/styles/wds-components/_pills.scss
  style-guide/styles/wds-components/index.scss
  style-guide/styles/wds-mixins/_dropdown-theming.scss
  style-guide/styles/wds-mixins/_pill-theming.scss
  style-guide/styles/wds-mixins/index.scss
  tests/dummy/app/controllers/application.js
  tests/dummy/app/router.js
  tests/dummy/app/templates/route-components/pills.hbs
  yarn.lock
Labels: deploy-docs-on-merge, publish-minor-on-merge

#462 Don't apply hover-like styles on focus state for button
  style-guide/styles/wds-mixins/_button-theming.scss
Labels: deploy-docs-on-merge, publish-minor-on-merge

#463 IW-4791 | wikia.org theming
  package.json
  style-guide/styles/wds-components/_global-navigation-wikia-org.scss
  style-guide/styles/wds-mixins/_wikia-org-theming.scss
  style-guide/styles/wds-mixins/index.scss
Labels: deploy-docs-on-merge, publish-minor-on-merge

#465 fix-release-test: Add test release script with option to pass
  README.md
  package.json
  scripts/release-test.sh
Labels: deploy-docs-on-merge, publish-minor-on-merge

#466 IW-4879 | removed old discussions theming swatches
  package.json
  style-guide/styles/wds-components/_global-navigation.scss
  style-guide/styles/wds-components/_on-site-notifications.scss
  style-guide/styles/wds-variables/_colors.scss
  tests/dummy/app/styles/app.scss
  tests/dummy/app/styles/components/_asset-box.scss
  tests/dummy/app/styles/components/_icon-box.scss
  tests/dummy/app/templates/base-styles/colors.hbs
Labels: deploy-docs-on-merge, publish-major-on-merge

#464 Missing social i18n
  i18n/de/design-system.json
  i18n/en/design-system.json
  i18n/es/design-system.json
  i18n/fi/design-system.json
  i18n/fr/design-system.json
  i18n/id/design-system.json
  i18n/it/design-system.json
  i18n/ja/design-system.json
  i18n/ko/design-system.json
  i18n/nl/design-system.json
  i18n/pl/design-system.json
  i18n/pt/design-system.json
  i18n/ru/design-system.json
  i18n/vi/design-system.json
  i18n/zh-hant/design-system.json
  i18n/zh/design-system.json
Labels: deploy-docs-on-merge, publish-minor-on-merge

#467 Check all publish labels before adding minor label
  Jenkinsfile-auto-deploy-marker
Labels: deploy-docs-on-merge, publish-patch-on-merge
